package logic

type Keyboard interface {
	PressSpace() error
	ReleaseSpace() error
	PressLeftShift() error
	ReleaseLeftShift() error
	PressRightAlt() error
	ReleaseRightAlt() error
	PressApostrophe() error
	ReleaseApostrophe() error
	PressComma() error
	ReleaseComma() error
	PressMinus() error
	ReleaseMinus() error
	PressDot() error
	ReleaseDot() error
	PressSlash() error
	ReleaseSlash() error
	Press0() error
	Release0() error
	Press1() error
	Release1() error
	Press2() error
	Release2() error
	Press3() error
	Release3() error
	Press4() error
	Release4() error
	Press5() error
	Release5() error
	Press6() error
	Release6() error
	Press7() error
	Release7() error
	Press8() error
	Release8() error
	Press9() error
	Release9() error
	PressSemicolon() error
	ReleaseSemicolon() error
	PressEqual() error
	ReleaseEqual() error
	PressA() error
	ReleaseA() error
	PressB() error
	ReleaseB() error
	PressC() error
	ReleaseC() error
	PressD() error
	ReleaseD() error
	PressE() error
	ReleaseE() error
	PressF() error
	ReleaseF() error
	PressG() error
	ReleaseG() error
	PressH() error
	ReleaseH() error
	PressI() error
	ReleaseI() error
	PressJ() error
	ReleaseJ() error
	PressK() error
	ReleaseK() error
	PressL() error
	ReleaseL() error
	PressM() error
	ReleaseM() error
	PressN() error
	ReleaseN() error
	PressO() error
	ReleaseO() error
	PressP() error
	ReleaseP() error
	PressQ() error
	ReleaseQ() error
	PressR() error
	ReleaseR() error
	PressS() error
	ReleaseS() error
	PressT() error
	ReleaseT() error
	PressU() error
	ReleaseU() error
	PressV() error
	ReleaseV() error
	PressW() error
	ReleaseW() error
	PressX() error
	ReleaseX() error
	PressY() error
	ReleaseY() error
	PressZ() error
	ReleaseZ() error
	PressLeftBrace() error
	ReleaseLeftBrace() error
	PressBackslash() error
	ReleaseBackslash() error
	PressRightBrace() error
	ReleaseRightBrace() error
	PressGrave() error
	ReleaseGrave() error
	PressEsc() error
	ReleaseEsc() error
	PressF1() error
	ReleaseF1() error
	PressF2() error
	ReleaseF2() error
	PressF3() error
	ReleaseF3() error
	PressF4() error
	ReleaseF4() error
	PressF5() error
	ReleaseF5() error
	PressF6() error
	ReleaseF6() error
	PressF7() error
	ReleaseF7() error
	PressF8() error
	ReleaseF8() error
	PressF9() error
	ReleaseF9() error
	PressF10() error
	ReleaseF10() error
	PressF11() error
	ReleaseF11() error
	PressF12() error
	ReleaseF12() error
	PressHome() error
	ReleaseHome() error
	PressEnd() error
	ReleaseEnd() error
	PressInsert() error
	ReleaseInsert() error
	PressDelete() error
	ReleaseDelete() error
	PressBackspace() error
	ReleaseBackspace() error
	PressEnter() error
	ReleaseEnter() error
	PressPageUp() error
	ReleasePageUp() error
	PressPageDown() error
	ReleasePageDown() error
	PressUp() error
	ReleaseUp() error
	PressDown() error
	ReleaseDown() error
	PressLeft() error
	ReleaseLeft() error
	PressRight() error
	ReleaseRight() error
	PressCapslock() error
	ReleaseCapslock() error
	PressTab() error
	ReleaseTab() error
}
